package com.zzzh.akhalteke_shipper.bean

class MainSendInfo(
     var goodsId:String = "",
     var shipperId:String = "",
     var shipperPortrait:String = "",
     var shipperName:String = "",
     var shipperPhone:String = "",
     var corporateName:String = "",
     var carLength:String = "",
     var carType:String = "",
     var goodsType:String = "",
     var weightVolume:String = "",
     var goodsName:String = "",
     var loadAreaCode:String = "",
     var loadAddress:String = "",
     var unloadAreaCode:String = "",
     var unloadAddress:String = "",
     var loadTime:String = "",
     var loadType:String = "",
     var payType:String = "",
     var registerTime:String = "",
     var cost:String = "",
     var comments:String = "",
     var createdTime:String = ""
)
//{
//    "goodsId":"GDS52444266510009",
//    "shipperId":"SHP52277490000001",
//    "shipperPortrait":"images/akhalteke/test/shipper/portrait/2019-03-11-17-52-56SHP52277490000001.jpg2019-03-11-17-52-56SHP52277490000001.jpg",
//    "shipperName":"张方波",
//    "shipperPhone":"18037878955",
//    "corporateName":"中州智慧",
//    "carLength":"3.8",
//    "carType":"保温",
//    "goodsType":"1",
//    "weightVolume":"30吨100m³",
//    "goodsName":"人",
//    "loadAreaCode":"开封市 禹王台区",
//    "loadAddress":"我的",
//    "unloadAreaCode":"锦州市 太和区",
//    "unloadAddress":"你的",
//    "loadTime":"1552579200000",
//    "loadType":"1",
//    "payType":"三段付",
//    "cost":"600000.0",
//    "comments":"6000",
//    "createdTime":"1552444266000"
//}